In [83]:
import numpy as np

In [84]:
#Vector Norms
#1 Euclidean Norm
x = np.array([[3],[4]])
np.linalg.norm(x, 2)

5.0

In [85]:
#2 Manhattan Norm
y = np.array([[3],[-8]])
np.linalg.norm(y, 1)

11.0

In [86]:
#3 Max Norm (Infinity Norm)
z = np.array([[3],[-8]])
np.linalg.norm(z, np.inf)

8.0

In [87]:
x,y = np.array([[-2],[2]]), np.array([[4],[-3]])
distance = np.linalg.norm(x-y, 2)
distance

7.810249675906656

In [88]:
# Vector Angles
x, y = np.array([[2],[0]]), np.array([[0],[2]])
cos_theta = (x.T@y)/(np.linalg.norm(x, 2) * np.linalg.norm(y, 2)) # type: ignore
cos_theta

array([[0.]])

In [89]:
cos_inverse = np.arccos(cos_theta)
cos_inverse

array([[1.57079633]])

In [90]:
degree = cos_inverse * ((180)/np.pi) #np.degrees
degree

array([[90.]])

In [91]:
# System of Linear equations
# x + 2y = 8
# 5x - 3y = 1
A = np.array([[0,2],[1,4]])
print (A)

[[0 2]
 [1 4]]


In [92]:
A.shape

(2, 2)

In [93]:
B = np.array([[3,1],[-3,2]])
print (B)

[[ 3  1]
 [-3  2]]


In [94]:
mat_sum = A + B # np.add(A, B)
mat_sum

array([[ 3,  3],
       [-2,  6]])

In [95]:
X = np.array([[0,2,4],
              [1,4,6],
              [9,6,7]])
print (X)

[[0 2 4]
 [1 4 6]
 [9 6 7]]


In [96]:
Y = np.array([[3,2,5],[7,4,7],[1,6,7]])
print (Y)

[[3 2 5]
 [7 4 7]
 [1 6 7]]


In [97]:
Z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (Z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
mat_sum2 = np.add(X,Y,Z)
mat_sum2

array([[ 3,  4,  9],
       [ 8,  8, 13],
       [10, 12, 14]])

In [99]:
# Matrix-Scalar multiplication
alpha = 2
mat_scalar = alpha * mat_sum2
mat_scalar

array([[ 6,  8, 18],
       [16, 16, 26],
       [20, 24, 28]])

In [100]:
# Matrix-vector multiplication
C = np.array([[0],[1]])
A@C

array([[2],
       [4]])

In [101]:
np.dot(A, B)

array([[-6,  4],
       [-9,  9]])

In [102]:
# Inverse Matrix
X_inverse = np.linalg.inv(X)
print(X_inverse)

[[ 0.30769231 -0.38461538  0.15384615]
 [-1.80769231  1.38461538 -0.15384615]
 [ 1.15384615 -0.69230769  0.07692308]]


In [103]:
I = X_inverse @ X
np.round(I)

array([[ 1., -0., -0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])

In [104]:
# Matrix transpose
print(X)
mat_transpose = X.T
mat_transpose

[[0 2 4]
 [1 4 6]
 [9 6 7]]


array([[0, 1, 9],
       [2, 4, 6],
       [4, 6, 7]])

In [105]:
# Hadamard product
B = A = np.array([[0, 2],[1, 4]])
A * B

array([[ 0,  4],
       [ 1, 16]])

In [106]:
# Gaussian Elimination method [Augmented Matrix]
# -> Addition and subtraction two equation
# -> Multiplication of an equation by a number
# -> Switching equations

In [107]:
M = np.array([[1,3,5],[2,2,-1],[1,3,2]])
Y = np.array([[-1],[1],[2]])
print(M)
print("\n\n")
print(Y)

[[ 1  3  5]
 [ 2  2 -1]
 [ 1  3  2]]



[[-1]
 [ 1]
 [ 2]]


In [108]:
solution = np.linalg.solve(M,Y)
solution

array([[-2.],
       [ 2.],
       [-1.]])

In [109]:
# A set of n linearly independent column vectors with n elements forms a basis.