In [1]:
import numpy as np
x = np.array([[1],[2],[3]])
x.shape

(3, 1)

In [2]:
print (f'A 3-D vector:\n{x}\n\n')

A 3-D vector:
[[1]
 [2]
 [3]]




In [3]:
y = np.array([[4],[5],[6]])
print (f'Sum:\n{x+y}\n\n')

Sum:
[[5]
 [7]
 [9]]




In [4]:
z = np.array([4,5])
print (x*z)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [7]:
a,b = 2, 3
x, y = np.array([[2], [3]]), np.array([[4],[5]])

a*x + b*y

array([[16],
       [21]])

In [12]:
c, d = np.array([[1],[2],[3]]), np.array([[4],[5],[6]])
# c=np.transpose(c)

c.T@d

array([[32]])